domain:
    path: /
    defaults: { _controller: AppBundle:Default:pickLanguage }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}/
    requirements:
        _locale: '%app.locales%'

JMSTranslationBundle_ui:
    resource: '@JMSTranslationBundle/Controller/'
    type:     annotation
    prefix:   /trans

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}/

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
