domain:
    path: /
    defaults: { _controller: AppBundle:Default:pickLanguage }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}/
    requirements:
        _locale: '%app.locales%'
