# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    referer_manager:
        class: AppBundle\Service\RefererManager
        arguments:
            - '@request_stack'
            - '@router'

    # JMS Translation Bundle
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    app.assets.versioning.gulp_buster:
        class: AppBundle\Asset\VersionStrategy\GulpBusterVersionStrategy
        arguments:
            - "%kernel.root_dir%/../busters.json"
            - "%%s?version=%%s"
        public: false
