# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    referer_manager:
        class: AppBundle\Service\RefererManager
        arguments:
            - '@request_stack'
            - '@router'

    # JMS Translation Bundle needed extension
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    app.assets.versioning.gulp_buster:
        class: AppBundle\Asset\VersionStrategy\GulpBusterVersionStrategy
        arguments:
            - "%kernel.root_dir%/../busters.json"
            - "%%s?version=%%s"
        public: false

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "%app.locales%"
            - "@security.authorization_checker"
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createLocalesMenu, alias: locales }
            - { name: knp_menu.menu_builder, method: createAuthenticationMenu, alias: authentication }
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }

    # Override Fos User Bundle default registration form
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    # Override Fos User Bundle default profile form
    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    # Prevents from impersonating admin user
    app.switch_user_listener:
        class: AppBundle\EventListener\SwitchUserListener
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }

    # Listens to suspicious behaviours
    app.suspicious_behaviour_subscriber:
        class: AppBundle\EventSubscriber\SuspiciousBehaviourSubscriber
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    # Sonata Admin classes
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
