# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    referer_manager:
        class: AppBundle\Service\RefererManager
        arguments:
            - '@request_stack'
            - '@router'

    # JMS Translation Bundle
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    app.assets.versioning.gulp_buster:
        class: AppBundle\Asset\VersionStrategy\GulpBusterVersionStrategy
        arguments:
            - "%kernel.root_dir%/../busters.json"
            - "%%s?version=%%s"
        public: false

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "%app.locales%"
            - "@security.authorization_checker"
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createLocalesMenu, alias: locales }
